language: csharp
mono: none
dotnet: 2.1.400

services:
  - redis-server

install:
  - dotnet restore

script:
  - dotnet build
  - dotnet test test/CoreTests/CoreTests.csproj
  - dotnet test test/StorageTests/StorageTests.csproj
  - dotnet test test/StreamProviderTests/StreamingTests.csproj